package upskills.database.model;
// Generated Sep 27, 2017 2:16:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Issue generated by hbm2java
 */
public class Issue  implements java.io.Serializable {


     private Integer id;
     private String report;
     private String trnFmly;
     private String trnGrp;
     private String trnType;
     private String sqlFilter;
     private String correctSource;
     private String differentType;
     private String explanation;
     private String fieldValues;

    public Issue() {
    }

    public Issue(String report, String trnFmly, String trnGrp, String trnType, String sqlFilter, String correctSource, String differentType, String explanation, String fieldValues) {
       this.report = report;
       this.trnFmly = trnFmly;
       this.trnGrp = trnGrp;
       this.trnType = trnType;
       this.sqlFilter = sqlFilter;
       this.correctSource = correctSource;
       this.differentType = differentType;
       this.explanation = explanation;
       this.fieldValues = fieldValues;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getReport() {
        return this.report;
    }
    
    public void setReport(String report) {
        this.report = report;
    }
    public String getTrnFmly() {
        return this.trnFmly;
    }
    
    public void setTrnFmly(String trnFmly) {
        this.trnFmly = trnFmly;
    }
    public String getTrnGrp() {
        return this.trnGrp;
    }
    
    public void setTrnGrp(String trnGrp) {
        this.trnGrp = trnGrp;
    }
    public String getTrnType() {
        return this.trnType;
    }
    
    public void setTrnType(String trnType) {
        this.trnType = trnType;
    }
    public String getSqlFilter() {
        return this.sqlFilter;
    }
    
    public void setSqlFilter(String sqlFilter) {
        this.sqlFilter = sqlFilter;
    }
    public String getCorrectSource() {
        return this.correctSource;
    }
    
    public void setCorrectSource(String correctSource) {
        this.correctSource = correctSource;
    }
    public String getDifferentType() {
        return this.differentType;
    }
    
    public void setDifferentType(String differentType) {
        this.differentType = differentType;
    }
    public String getExplanation() {
        return this.explanation;
    }
    
    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }
    public String getFieldValues() {
        return this.fieldValues;
    }
    
    public void setFieldValues(String fieldValues) {
        this.fieldValues = fieldValues;
    }

}


