package upskills.database.model;
// Generated Sep 28, 2017 4:22:22 PM by Hibernate Tools 4.3.1



/**
 * Trade generated by hbm2java
 */
public class Trade  implements java.io.Serializable {


     private TradeId id;
     private Issue issue;
     private String instrument;
     private String currency;
     private String portfolio;
     private String trnFmly;
     private String trnGrp;
     private String trnType;
     private String trnStatus;

    public Trade() {
    }

	
    public Trade(TradeId id) {
        this.id = id;
    }
    public Trade(TradeId id, Issue issue, String instrument, String currency, String portfolio, String trnFmly, String trnGrp, String trnType, String trnStatus) {
       this.id = id;
       this.issue = issue;
       this.instrument = instrument;
       this.currency = currency;
       this.portfolio = portfolio;
       this.trnFmly = trnFmly;
       this.trnGrp = trnGrp;
       this.trnType = trnType;
       this.trnStatus = trnStatus;
    }
   
    public TradeId getId() {
        return this.id;
    }
    
    public void setId(TradeId id) {
        this.id = id;
    }
    public Issue getIssue() {
        return this.issue;
    }
    
    public void setIssue(Issue issue) {
        this.issue = issue;
    }
    public String getInstrument() {
        return this.instrument;
    }
    
    public void setInstrument(String instrument) {
        this.instrument = instrument;
    }
    public String getCurrency() {
        return this.currency;
    }
    
    public void setCurrency(String currency) {
        this.currency = currency;
    }
    public String getPortfolio() {
        return this.portfolio;
    }
    
    public void setPortfolio(String portfolio) {
        this.portfolio = portfolio;
    }
    public String getTrnFmly() {
        return this.trnFmly;
    }
    
    public void setTrnFmly(String trnFmly) {
        this.trnFmly = trnFmly;
    }
    public String getTrnGrp() {
        return this.trnGrp;
    }
    
    public void setTrnGrp(String trnGrp) {
        this.trnGrp = trnGrp;
    }
    public String getTrnType() {
        return this.trnType;
    }
    
    public void setTrnType(String trnType) {
        this.trnType = trnType;
    }
    public String getTrnStatus() {
        return this.trnStatus;
    }
    
    public void setTrnStatus(String trnStatus) {
        this.trnStatus = trnStatus;
    }




}


